// ═══════════════════════════════════════════════════════════════
// QUASAR Web3 Provider v3.0 — TON Connect 2.0 + on-chain getters
// Synchronized with QuasarMaster & QuasarDeFi contracts.
// F-03: two-step QSR deposit before dependent calls.
// F-16: pool/ecosystem stats and balances read from real getters.
// ═══════════════════════════════════════════════════════════════
import { beginCell, Cell, Address } from 'https://esm.sh/@ton/core@0.63.1?bundle';

let tonConnectUI = null;
let isInitialized = false;
let connectedAddress = null;

// ─── Operation Codes (generated by Tact and mirrored from the ABI) ───
const OP = {
    STAKE_QSR: 3203459332,
    UNSTAKE_QSR: 4284693473,
    CLAIM_STAKE: 155852668,
    ADD_LIQUIDITY: 146776957,
    REMOVE_LIQUIDITY: 3287568056,
    SWAP_TO_TON: 1118291020,
    SWAP_TO_QSR: 3020093557,
    CLAIM_FARM: 1360209904,
    REFUND_PENDING_QSR: 1093959957,
};

// TEP-74 standard jetton transfer opcode, used for the QSR deposit (F-03).
const JETTON_TRANSFER_OP = 0x0f8a7ea5;
// Forward TON attached to a jetton transfer so the receiving contract's
// wallet emits a TokenNotification (this is what credits the pending deposit).
const DEPOSIT_FORWARD_TON = 10000000n; // 0.01 TON

// ─── Gas amounts (nanoTON) ───
const GAS = {
    STAKE: '50000000',      // 0.05 TON
    SWAP: '100000000',      // 0.1 TON
    LIQUIDITY: '100000000', // 0.1 TON base
    CLAIM: '50000000',      // 0.05 TON
    DEPOSIT: '50000000',    // 0.05 TON for the jetton transfer + forward
};

const NANO = 1000000000n;
const ONE_KILO = 1000n;

// ─── Initialize TON Connect ───
export function initTonConnect() {
    if (typeof window === 'undefined') return;
    if (isInitialized) return;

    if (!window.TON_CONNECT_UI) {
        console.error('[QUASAR] TON Connect UI not loaded');
        setTimeout(initTonConnect, 1000);
        return;
    }

    const config = window.QUASAR_CONFIG || {};

    tonConnectUI = new window.TON_CONNECT_UI.TonConnectUI({
        // F-02: same-origin fallback instead of the dead hardcoded domain
        manifestUrl: config.manifestUrl || './tonconnect-manifest.json',
        buttonRootId: config.buttonRootId || 'ton-connect',
    });

    tonConnectUI.onStatusChange(wallet => {
        updateWalletUI(wallet);
    });

    isInitialized = true;
    console.log('[QUASAR] TON Connect initialized');
}

// ─── Toncenter helpers (F-16: real getters) ───
function networkEndpoint() {
    const config = window.QUASAR_CONFIG || {};
    const network = config.network === 'mainnet' ? 'mainnet' : 'testnet';
    return config.toncenter?.[network] || `https://${network}.toncenter.com/api/v2/jsonRPC`;
}

function addressStackArg(address) {
    return ['slice', { bytes: beginCell().storeAddress(Address.parse(address)).endCell().toB64() }];
}

// Runs a contract getter through the Toncenter JSON-RPC `runGetMethod`
// endpoint and returns the raw stack. No placeholder data is ever used.
async function runGetMethod(address, method, stack = []) {
    if (!address) throw new Error(`${method}: contract address is not configured`);
    const res = await fetch(networkEndpoint(), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            id: '1',
            jsonrpc: '2.0',
            method: 'runGetMethod',
            params: { address, method, stack },
        }),
    });
    const data = await res.json();
    if (!data || !data.result) {
        throw new Error(`${method}: ${data?.error?.message || 'getter call failed'}`);
    }
    return data.result.stack || [];
}

function stackValue(item) {
    if (item == null) return undefined;
    return Array.isArray(item) ? item[1] : item.value;
}

function parseNumber(item) {
    const value = stackValue(item);
    if (value == null) return 0n;
    if (typeof value === 'object') return BigInt(value.bytes ? BufferFreeBase64ToBigInt(value.bytes) : 0);
    return BigInt(value);
}

function parseAddress(item) {
    const value = stackValue(item);
    const bytes = typeof value === 'object' ? value.bytes : value;
    if (!bytes) return null;
    return Cell.fromBase64(bytes).beginParse().loadAddress().toString();
}

// Tuple (num) cells are returned as a big-endian byte string; convert safely.
function BufferFreeBase64ToBigInt(b64) {
    const bin = atob(b64);
    let out = 0n;
    for (let i = 0; i < bin.length; i++) out = (out << 8n) | BigInt(bin.charCodeAt(i));
    return out;
}

// ─── Formatting helpers ───
function fmt(value, decimals, suffix) {
    const base = 10n ** BigInt(decimals);
    const whole = value / base;
    const frac = (value % base).toString().padStart(decimals, '0').slice(0, 4);
    return `${whole}.${frac}${suffix ? ' ' + suffix : ''}`;
}
const fmtTon = v => fmt(v, 9, 'TON');
const fmtQsr = v => fmt(v, 9, 'QSR');

function setText(id, text) {
    const el = document.getElementById(id);
    if (el) el.textContent = text;
}

// ─── UI Updates ───
function updateWalletUI(wallet) {
    const addrEl = document.getElementById('wallet-address');
    const appSec = document.getElementById('defi');

    if (!wallet) {
        connectedAddress = null;
        window.__qsrOwner = null;
        if (addrEl) addrEl.textContent = 'Not connected';
        if (appSec) appSec.classList.remove('active');
        return;
    }

    const addr = wallet.account.address;
    connectedAddress = addr;
    window.__qsrOwner = addr;
    const short = addr.slice(0, 6) + '...' + addr.slice(-4);

    if (addrEl) addrEl.textContent = short;
    if (appSec) appSec.classList.add('active');

    // These are independent reads; run them together so a slow getter does
    // not block the wallet header from rendering.
    Promise.allSettled([loadBalances(addr), loadQsrBalance(addr), loadPoolStats()]);
}

// ─── Balance Loader ───
async function loadBalances(address) {
    try {
        const res = await fetch(`${networkEndpoint()}/getAddressBalance?address=${address}`);
        const data = await res.json();
        if (data && data.result) {
            setText('ton-balance', fmt(BigInt(data.result), 9, 'TON'));
        }
    } catch (e) {
        console.error('[QUASAR] Balance load error:', e);
    }
}

// QSR balance is read from the user's jetton wallet (F-16).
async function loadQsrBalance(address) {
    const config = window.QUASAR_CONFIG || {};
    const master = config.addresses?.master;
    if (!master) return;
    try {
        const stack = await runGetMethod(master, 'get_wallet_address', [addressStackArg(address)]);
        const wallet = parseAddress(stack[0]);
        if (!wallet) return;
        const data = await runGetMethod(wallet, 'get_wallet_data');
        setText('qsr-balance', fmtQsr(parseNumber(data[0])));
    } catch (e) {
        console.warn('[QUASAR] QSR balance error:', e);
    }
}

// ─── Pool Stats (F-16: filled from live contract getters) ───
export async function loadPoolStats() {
    const config = window.QUASAR_CONFIG || {};
    const defi = config.addresses?.defi;
    if (!defi) return null;
    try {
        const pool = await runGetMethod(defi, 'poolInfo');
        const totalLp = parseNumber(pool[0]);
        const tonReserve = parseNumber(pool[1]);
        const qsrReserve = parseNumber(pool[2]);
        setText('pool-ton-reserve', fmtTon(tonReserve));
        setText('pool-qsr-reserve', fmtQsr(qsrReserve));
        setText('pool-total-lp', totalLp.toString());

        const farm = await runGetMethod(defi, 'farmInfo');
        const staked = parseNumber(farm[0]);
        const rewardPerSecond = parseNumber(farm[1]);
        setText('pool-total-staked', fmtQsr(staked));

        // Farm APY = rewardPerSecond * secondsPerYear / staked, as a percent.
        let apy = 0;
        if (staked > 0n) {
            apy = Number((rewardPerSecond * 31536000n * 10000n) / staked) / 100;
        }
        setText('pool-farm-apy', (staked > 0n ? apy.toFixed(2) : '0.00') + '%');
        return { totalLp, tonReserve, qsrReserve, staked, rewardPerSecond, apy };
    } catch (e) {
        console.warn('[QUASAR] Pool stats error:', e);
        return null;
    }
}

// Returns the caller's pending QSR deposit on a contract (0 when none).
export async function pendingDeposit(target, user) {
    const config = window.QUASAR_CONFIG || {};
    const address = target === 'defi' ? config.addresses?.defi : config.addresses?.master;
    if (!address || !user) return 0n;
    try {
        const method = target === 'defi' ? 'pendingQsrDeposit' : 'get_pending_qsr_deposit';
        const stack = await runGetMethod(address, method, [addressStackArg(user)]);
        return parseNumber(stack[0]);
    } catch (e) {
        console.warn('[QUASAR] pendingDeposit error:', e);
        return 0n;
    }
}

// Quote against the same CPMM equations used by QuasarDeFi. The minimum
// output must be derived from the expected output, not from the input amount
// (QSR and TON are different assets and therefore different units).
export async function quoteSwap(direction, amountNano) {
    if (!amountNano || amountNano <= 0n) return 0n;
    const config = window.QUASAR_CONFIG || {};
    const defi = config.addresses?.defi;
    if (!defi) throw new Error('DeFi address is not configured');
    const [pool, feeStack] = await Promise.all([
        runGetMethod(defi, 'poolInfo'),
        runGetMethod(defi, 'feeConfig')
    ]);
    const tonReserve = parseNumber(pool[1]);
    const qsrReserve = parseNumber(pool[2]);
    const feeBps = parseNumber(feeStack[0]);
    if (tonReserve <= 0n || qsrReserve <= 0n) return 0n;

    if (direction === 'to-ton') {
        const gross = (amountNano * tonReserve) / (qsrReserve + amountNano);
        return gross - (gross * feeBps) / 10000n;
    }

    const gross = (amountNano * qsrReserve) / (tonReserve + amountNano);
    return gross - (gross * feeBps) / 10000n;
}

// ─── BOC Builder ───
function buildPayload(op, ...args) {
    const cell = beginCell();
    cell.storeUint(op, 32);
    for (const arg of args) {
        if (typeof arg === 'bigint') {
            cell.storeCoins(arg);
        } else if (typeof arg === 'number') {
            cell.storeUint(arg, 32);
        } else {
            throw new TypeError(`Unsupported payload argument: ${typeof arg}`);
        }
    }
    const bytes = cell.endCell().toBoc();
    let binary = '';
    for (const byte of bytes) binary += String.fromCharCode(byte);
    return btoa(binary);
}

// ─── Transaction Sender ───
async function sendTx(address, amount, payload) {
    if (!tonConnectUI) {
        window.showToast?.('Connect wallet first!', 'error');
        return null;
    }

    const target = address;
    if (!target || target.includes('YOUR_QUASAR_')) {
        window.showToast?.('Contract addresses are not configured yet', 'error');
        return null;
    }

    try {
        const tx = await tonConnectUI.sendTransaction({
            validUntil: Math.floor(Date.now() / 1000) + 300,
            messages: [{ address: target, amount, payload }],
        });
        window.showToast?.('Transaction sent!', 'success');
        return tx;
    } catch (e) {
        console.error('[QUASAR] TX error:', e);
        window.showToast?.('Transaction failed: ' + (e.message || e), 'error');
        throw e;
    }
}

// ─── QSR Deposit (F-03) ───
// QuasarMaster (staking) and QuasarDeFi (liquidity, swaps) consume QSR from a
// pending deposit credited when the user sends jettons to the contract. This
// builds a TEP-74 transfer from the user's jetton wallet to the contract's
// wallet; the non-zero forward TON makes the wallet emit a TokenNotification
// that credits the pending deposit on the contract.
export async function depositQsr(target, amountNano) {
    if (!connectedAddress) {
        window.showToast?.('Connect wallet first!', 'error');
        return null;
    }
    if (!amountNano || amountNano <= 0n) {
        window.showToast?.('Enter a valid QSR amount', 'error');
        return null;
    }
    const config = window.QUASAR_CONFIG || {};
    const master = config.addresses?.master;
    const contract = target === 'defi' ? config.addresses?.defi : master;
    if (!master || !contract) {
        window.showToast?.('Contract addresses are not configured yet', 'error');
        return null;
    }
    try {
        const stack = await runGetMethod(master, 'get_wallet_address', [addressStackArg(connectedAddress)]);
        const wallet = parseAddress(stack[0]);
        if (!wallet) throw new Error('jetton wallet not found');

        const payload = beginCell()
            .storeUint(JETTON_TRANSFER_OP, 32)
            .storeUint(0, 64)                       // query_id
            .storeCoins(amountNano)                 // amount
            .storeAddress(Address.parse(contract))  // destination = target contract
            .storeAddress(Address.parse(connectedAddress)) // response destination
            .storeBit(0)                            // no custom payload
            .storeCoins(DEPOSIT_FORWARD_TON)        // forward TON -> TokenNotification
            .storeBit(0)                            // forward payload: empty, inline
            .endCell();

        return sendTx(wallet, GAS.DEPOSIT, payload.toBoc().toString('base64'));
    } catch (e) {
        console.error('[QUASAR] Deposit error:', e);
        window.showToast?.('Deposit failed: ' + (e.message || e), 'error');
        return null;
    }
}

// ─── Contract Operations ───

export async function stakeQsr(amountNano) {
    if (!amountNano || amountNano <= 0n) {
        window.showToast?.('Enter valid QSR amount', 'error'); return;
    }
    const config = window.QUASAR_CONFIG || {};
    return sendTx(config.addresses?.master, GAS.STAKE, buildPayload(OP.STAKE_QSR, amountNano));
}

export async function unstakeQsr(amountNano) {
    if (!amountNano || amountNano <= 0n) {
        window.showToast?.('Enter valid amount', 'error'); return;
    }
    const config = window.QUASAR_CONFIG || {};
    return sendTx(config.addresses?.master, GAS.STAKE, buildPayload(OP.UNSTAKE_QSR, amountNano));
}

export async function claimStakingRewards() {
    const config = window.QUASAR_CONFIG || {};
    return sendTx(config.addresses?.master, GAS.CLAIM, buildPayload(OP.CLAIM_STAKE));
}

export async function addLiquidity(tonAmount, qsrAmount) {
    if (!tonAmount || !qsrAmount || tonAmount <= 0n || qsrAmount <= 0n) {
        window.showToast?.('Enter valid amounts', 'error'); return;
    }
    const config = window.QUASAR_CONFIG || {};
    const totalAmount = (tonAmount + BigInt(GAS.LIQUIDITY)).toString();
    return sendTx(config.addresses?.defi, totalAmount, buildPayload(OP.ADD_LIQUIDITY, tonAmount, qsrAmount));
}

export async function removeLiquidity(lpAmount) {
    if (!lpAmount || lpAmount <= 0n) {
        window.showToast?.('Enter valid LP amount', 'error'); return;
    }
    const config = window.QUASAR_CONFIG || {};
    return sendTx(config.addresses?.defi, GAS.LIQUIDITY, buildPayload(OP.REMOVE_LIQUIDITY, lpAmount));
}

export async function swapToTon(qsrAmount, minTonOut) {
    if (!qsrAmount || qsrAmount <= 0n) {
        window.showToast?.('Enter valid QSR amount', 'error'); return;
    }
    const config = window.QUASAR_CONFIG || {};
    return sendTx(config.addresses?.defi, GAS.SWAP, buildPayload(OP.SWAP_TO_TON, qsrAmount, minTonOut || 1n));
}

export async function swapToQsr(tonAmount, minQsrOut) {
    if (!tonAmount || tonAmount <= 0n) {
        window.showToast?.('Enter valid TON amount', 'error'); return;
    }
    const config = window.QUASAR_CONFIG || {};
    const totalAmount = (tonAmount + BigInt(GAS.SWAP)).toString();
    return sendTx(config.addresses?.defi, totalAmount, buildPayload(OP.SWAP_TO_QSR, tonAmount, minQsrOut || 1n));
}

export async function claimFarmRewards() {
    const config = window.QUASAR_CONFIG || {};
    return sendTx(config.addresses?.defi, GAS.CLAIM, buildPayload(OP.CLAIM_FARM));
}

export async function refundPendingQsr() {
    const config = window.QUASAR_CONFIG || {};
    return sendTx(config.addresses?.defi, GAS.CLAIM, buildPayload(OP.REFUND_PENDING_QSR));
}

// ─── Expose to window ───
if (typeof window !== 'undefined') {
    window.stakeQsr = stakeQsr;
    window.unstakeQsr = unstakeQsr;
    window.claimStakingRewards = claimStakingRewards;
    window.addLiquidity = addLiquidity;
    window.removeLiquidity = removeLiquidity;
    window.swapToTon = swapToTon;
    window.swapToQsr = swapToQsr;
    window.claimFarmRewards = claimFarmRewards;
    window.refundPendingQsr = refundPendingQsr;
    window.depositQsr = depositQsr;
    window.pendingDeposit = pendingDeposit;
    window.quoteSwap = quoteSwap;
    window.loadPoolStats = loadPoolStats;
    window.initTonConnect = initTonConnect;
}
